config/routes.rb
Rails.application.routes.draw do
  resources :offers
  resource :profile, only: %i[edit update] do
    get :edit_recipient, on: :member
    get :edit_volunteer, on: :member
  end
  resource :need, as: :my_need, only: %i[show edit update destroy]
  resources :needs, only: %i[index show] do
    resources :offers, only: %i[index create]
  end
  post 'auth', to: 'auth#create'
  get 'auth', to: 'auth#activate', as: 'activate_auth'
  get 'qa', to: 'main#qa', as: 'qa'
  get 'tos', to: 'main#tos', as: 'tos'
  get 'privacy_policy', to: 'main#privacy_policy', as: 'privacy_policy'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  root 'main#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/need.rb
class Need < ApplicationRecord
  belongs_to :user
  has_many :offers
  attr_writer :lc_lat, :lc_lng
  before_validation :set_location
  validates :location, presence: { message: 'please click a map to select your location' }
  validates :description, presence: true

  scope :within_10km_from, -> (location) {
    where(%{
     ST_Distance(location, '%s') < %d
    } % [location, 10000])
  }

  def set_location
    self.location = "POINT(#{@lc_lng} #{@lc_lat})"
  end

  def lc_lat
    location&.latitude
  end
  def lc_lng
    location&.longitude
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  belongs_to :need

  validates :user_id, uniqueness: { scope: :need_id, message: 'offer has already been sent' }
  validates :message, presence: true
  validates :contact_info, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  before_create :set_sid
  validates :name, presence: true, on: :update
  validates :bio, presence: true, on: :update
  validates :location, presence: { message: 'please set a marker near your location' }, on: :update, if: :volunteer?

  enum kind: { guest: 0, recipient: 1, volunteer: 2 }

  has_one :need, dependent: :destroy
  has_many :offers
  attr_writer :lc_lat, :lc_lng
  before_validation :set_location

  def lc_lat
    location&.latitude
  end
  def lc_lng
    location&.longitude
  end

  private
  def set_sid
    self.sid = SecureRandom.alphanumeric(8)
  end

  def set_location
    return if !@lc_lat || !@lc_lng
    self.location = "POINT(#{@lc_lng} #{@lc_lat})"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  helper_method :current_user, :logged_in?
  add_flash_types :success, :error, :warning

  before_action :verify_account
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: :index

  rescue_from Pundit::NotAuthorizedError do
    if logged_in?
      redirect_to root_path, error: t('application.prohibited')
    else
      redirect_to root_path, warning: t('application.log_in_first')
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  private
  def verify_account
    return unless logged_in?
    return redirect_to edit_profile_path if current_user.guest?
    return redirect_to edit_volunteer_profile_path if current_user.volunteer? && !current_user.valid?
    return redirect_to edit_recipient_profile_path if current_user.recipient? && !current_user.valid?
  end

  def render_with_turbolinks(*options, &block)
    html = render_to_string(*options, &block)

    script = <<-SCRIPT
      (function(){
        Turbolinks.clearCache();
        var doc = document.implementation.createHTMLDocument('response');
        doc.documentElement.innerHTML = "#{ActionController::Base.helpers.j(html)}";
        document.documentElement.replaceChild(doc.body, document.body);
        Turbolinks.dispatch('turbolinks:load');
        window.scroll(0, 0);
      })();
    SCRIPT

    self.status = 200
    self.response_body = script
    response.content_type = 'text/javascript'
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def create
    authorize :auth
    user = User.find_or_create_by(email: params[:email])
    UserMailer.with(user: user).sign_up.deliver_now
    redirect_to root_path, success: t('.link_sent')
  end

  def activate
    authorize :auth
    user_id = JwtAuth.decrypt(params[:token])
    session[:user_id] = User.find(user_id).id
    redirect_to root_path, success: t('.logged_in')
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_after_action :verify_policy_scoped, only: :index
  skip_after_action :verify_authorized, only: %i[qa tos privacy_policy]
  before_action :redirect_to_need, only: :index

  def index
  end

  def qa
  end

  def tos
  end

  def privacy_policy
  end

  private

  # we want to keep recipients on their need page
  def redirect_to_need
    return unless logged_in?
    return unless current_user.recipient?
    return if current_user.need.nil?
    redirect_to my_need_path
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  def index
    authorize Need
    @needs = policy_scope(Need)
    @needs_json = @needs.to_json(only: [:id, :description], methods: [:lc_lat, :lc_lng])
  end

  def show
    @need = params[:id] ? policy_scope(Need).find(params[:id]) : current_user.need
    authorize @need
  end

  def edit
    @need = current_user.need || current_user.build_need
    authorize @need
  end

  def update
    @need = current_user.need || current_user.build_need
    authorize @need
    if @need.update_attributes(need_params)
      redirect_to my_need_path, success: t('.success')
    else
      render_with_turbolinks 'edit'
    end
  end

  def destroy
    @need = current_user.need
    authorize @need
    @need.destroy
    redirect_to root_path, success: t('.success')
  end

  private
  def need_params
    params.require(:need).permit(:description, :lc_lat, :lc_lng)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def create
    @need = Need.find(params[:need_id])
    @offer = current_user.offers.build(offer_params.merge(need_id: @need.id))
    authorize @offer

    if @offer.save
      OffersMailer.with(user: @need.user, offer: @offer).received_offer.deliver_now
      redirect_to need_path(@need), success: 'Offer to help was successfully sent.'
    else
      render 'needs/show'
    end
  end

  private
    def offer_params
      params.require(:offer).permit(:message, :contact_info)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  skip_before_action :verify_account

  def edit
    authorize :profile
  end

  def edit_recipient
    authorize :profile
    current_user.update_column(:kind, 1)
  end

  def edit_volunteer
    authorize :profile
    current_user.update_column(:kind, 2)
  end

  def update
    authorize :profile
    if current_user.update(profile_params)
      next_url = current_user.volunteer? ? root_path : edit_my_need_path
      redirect_to next_url, success: t('.success')
    else
      render_with_turbolinks current_user.volunteer? ? 'edit_volunteer' : 'edit_recipient'
    end
  end

  private
  def profile_params
    params.require(:user).permit(:name, :bio, :lc_lat, :lc_lng)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpMeTo.live</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css' rel='stylesheet' />
    <script>
      mapboxgl.accessToken = '<%= ENV['MAPBOXJS_TOKEN'] %>';
    </script>
    <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.min.js"></script>
    <link
      rel="stylesheet"
      href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.4.2/mapbox-gl-geocoder.css"
      type="text/css"
    />
    <!-- Promise polyfill script required to use Mapbox GL Geocoder in IE 11 -->
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
    <script>
      window.I18n = <%= I18n.backend.send(:translations)[I18n.locale][:javascript].to_json.html_safe %>
    </script>
  </head>

  <body>
    <div class="alerts">
      <% flash.each do |type, msg| %>
        <div class="alert alert-<%= type %>">
          <%= msg %>
        </div>
      <% end %>
    </div>
    <div class="alerts">
    </div>
    <div class="container mx-auto mb-4 p-4">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="w-full md:w-1/2 mx-auto flex flex-col">
  <h1 class="text-4xl"><%= t('.welcome') %></h1>
  <h3 class="text-2xl"><%= t('.line1') %></h3>
  <h3 class="text-lg"><%= t('.line2') %></h3>
  <h3 class="text-xl mt-4">
    <%= t('.currently') %>
    <%= t('.volunteer', count: User.where(kind: :volunteer).count) %>
    <%= t('common.and') %>
    <%= t('.recipient', count: User.where(kind: :recipient).count) %>
  </h3>
  <% if logged_in? && current_user.recipient? %>
    <%= link_to current_user.need ? t('.view_your_request') : t('.create_request'), edit_my_need_path, class: 'my-2 p-6 bg-blue-500 block text-white text-2xl self-center' %>
  <% elsif logged_in? %>
    <%= link_to t('.view_requests'), needs_path, class: 'my-2 p-6 bg-blue-500 block text-white text-xl self-center' %>
  <% else %>
    <%= form_with url: '/auth', method: :post, class: "my-8 flex flex-col items-center w-full" do %>
      <h3 class="text-lg mb-1 w-full"><%= t('.call_to_action') %></h3>
      <div class="flex w-full">
        <%= email_field_tag :email, '', class: "string text-xl border rounded p-2 flex-1", autofocus: true %>
        <%= submit_tag t('common.go'), class: "rounded bg-blue-600 px-6 py-2 text-xl ml-2 text-white" %>
      </div>
      <p class="text-gray-800 w-full text-sm">
        <%= t('.you_accept') %> <a href="/tos" class='text-blue-500'><%= t('.tos') %></a> <%= t('common.and') %> <a href="/privacy_policy" class='text-blue-500'><%= t('.privacy_policy') %></a>
      </p>
    <% end %>
  <% end %>
</div>

<div class="w-full md:w-1/2 mx-auto flex flex-col">
  <h3 class="text-xl"><%= t('.how_works') %></h3>
  <p><%= t('.service_description') %></p>

  <h3 class="text-xl">
    <%= t('.questions') %>
    <a href="/qa" class="text-blue-500 underline"><%= t('.click_here') %></a>
  </h3>
</div>

app/views/main/qa.html.erb
<h3 class="text-xl mt-8 mb-4"><%= t('.for_volunteers') %></h3>
<blockquote class="font-bold"><%= t('.volunteer_1_question') %></blockquote>
<p><%= t('.volunteer_1_answer') %></p>
<blockquote class="font-bold"><%= t('.volunteer_2_question') %></blockquote>
<p><%= t('.volunteer_2_answer') %></p>
<blockquote class="font-bold"><%= t('.volunteer_3_question') %></blockquote>
<p><%= t('.volunteer_3_answer') %></p>

<h3 class="text-xl mt-8 mb-4"><%= t('.for_recipients') %></h3>
<blockquote class="font-bold"><%= t('.recipient_1_question') %></blockquote>
<p><%= t('.recipient_1_answer') %></p>

<h3 class="text-xl mt-8 mb-4"><%= t('.for_everyone') %></h3>
<blockquote class="font-bold"><%= t('.everyone_1_question') %></blockquote>
<p><%= t('.everyone_1_answer') %></p>
<blockquote class="font-bold"><%= t('.everyone_2_question') %></blockquote>
<p><%= t('.everyone_2_answer') %></p>
<blockquote class="font-bold"><%= t('.everyone_3_question') %></blockquote>
<p><%= t('.everyone_3_answer') %></p>

app/views/main/tos.html.erb
<h1 class="text-xl">Terms and conditions</h1>
<p>These terms and conditions (&quot;Terms&quot;, &quot;Agreement&quot;) are an agreement between Website Operator (&quot;Website Operator&quot;, &quot;us&quot;, &quot;we&quot; or &quot;our&quot;) and you (&quot;User&quot;, &quot;you&quot; or &quot;your&quot;). This Agreement sets forth the general terms and conditions of your use of the <a target="_blank" rel="nofollow" href="https://helpmeto.live">helpmeto.live</a> website and any of its products or services (collectively, &quot;Website&quot; or &quot;Services&quot;).</p>
<h2 class="text-lg mt-4">Accounts and membership</h2>
<p>You must be at least 18 years of age to use this Website. By using this Website and by agreeing to this Agreement you warrant and represent that you are at least 18 years of age. If you create an account on the Website, you are responsible for maintaining the security of your account and you are fully responsible for all activities that occur under the account and any other actions taken in connection with it. We may, but have no obligation to, monitor and review new accounts before you may sign in and use our Services. Providing false contact information of any kind may result in the termination of your account. You must immediately notify us of any unauthorized uses of your account or any other breaches of security. We will not be liable for any acts or omissions by you, including any damages of any kind incurred as a result of such acts or omissions. We may suspend, disable, or delete your account (or any part thereof) if we determine that you have violated any provision of this Agreement or that your conduct or content would tend to damage our reputation and goodwill. If we delete your account for the foregoing reasons, you may not re-register for our Services. We may block your email address and Internet protocol address to prevent further registration.</p>
<h2 class="text-lg mt-4">User content</h2>
<p>We do not own any data, information or material (&quot;Content&quot;) that you submit on the Website in the course of using the Service. You shall have sole responsibility for the accuracy, quality, integrity, legality, reliability, appropriateness, and intellectual property ownership or right to use of all submitted Content. We may, but have no obligation to, monitor and review Content on the Website submitted or created using our Services by you. Unless specifically permitted by you, your use of the Website does not grant us the license to use, reproduce, adapt, modify, publish or distribute the Content created by you or stored in your user account for commercial, marketing or any similar purpose. But you grant us permission to access, copy, distribute, store, transmit, reformat, display and perform the Content of your user account solely as required for the purpose of providing the Services to you. Without limiting any of those representations or warranties, we have the right, though not the obligation, to, in our own sole discretion, refuse or remove any Content that, in our reasonable opinion, violates any of our policies or is in any way harmful or objectionable.</p>
<h2 class="text-lg mt-4">Backups</h2>
<p>We perform regular backups of the Website and  Content, however, these backups are for our own administrative purposes only and are in no way guaranteed. You are responsible for maintaining your own backups of your data. We do not provide any sort of compensation for lost or incomplete data in the event that backups do not function properly. We will do our best to ensure complete and accurate backups, but assume no responsibility for this duty.</p>
<h2 class="text-lg mt-4">Links to other websites</h2>
<p>Although this Website may link to other websites, we are not, directly or indirectly, implying any approval, association, sponsorship, endorsement, or affiliation with any linked website, unless specifically stated herein. We are not responsible for examining or evaluating, and we do not warrant the offerings of, any businesses or individuals or the content of their websites. We do not assume any responsibility or liability for the actions, products, services, and content of any other third-parties. You should carefully review the legal statements and other conditions of use of any website which you access through a link from this Website. Your linking to any other off-site websites is at your own risk.</p>
<h2 class="text-lg mt-4">Prohibited uses</h2>
<p>In addition to other terms as set forth in the Agreement, you are prohibited from using the Website or its Content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, provincial or state regulations, rules, laws, or local ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code that will or may be used in any way that will affect the functionality or operation of the Service or of any related website, other websites, or the Internet; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Service or any related website, other websites, or the Internet. We reserve the right to terminate your use of the Service or any related website for violating any of the prohibited uses.</p>
<h2 class="text-lg mt-4">Limitation of liability</h2>
<p>To the fullest extent permitted by applicable law, in no event will Website Operator, its affiliates, officers, directors, employees, agents, suppliers or licensors be liable to any person for (a): any indirect, incidental, special, punitive, cover or consequential damages (including, without limitation, damages for lost profits, revenue, sales, goodwill, use of content, impact on business, business interruption, loss of anticipated savings, loss of business opportunity) however caused, under any theory of liability, including, without limitation, contract, tort, warranty, breach of statutory duty, negligence or otherwise, even if Website Operator has been advised as to the possibility of such damages or could have foreseen such damages. To the maximum extent permitted by applicable law, the aggregate liability of Website Operator and its affiliates, officers, employees, agents, suppliers and licensors, relating to the services will be limited to an amount greater of one dollar or any amounts actually paid in cash by you to Website Operator for the prior one month period prior to the first event or occurrence giving rise to such liability. The limitations and exclusions also apply if this remedy does not fully compensate you for any losses or fails of its essential purpose.</p>
<h2 class="text-lg mt-4">Indemnification</h2>
<p>You agree to indemnify and hold Website Operator and its affiliates, directors, officers, employees, and agents harmless from and against any liabilities, losses, damages or costs, including reasonable attorneys' fees, incurred in connection with or arising from any third-party allegations, claims, actions, disputes, or demands asserted against any of them as a result of or relating to your Content, your use of the Website or Services or any willful misconduct on your part.</p>
<h2 class="text-lg mt-4">Severability</h2>
<p>All rights and restrictions contained in this Agreement may be exercised and shall be applicable and binding only to the extent that they do not violate any applicable laws and are intended to be limited to the extent necessary so that they will not render this Agreement illegal, invalid or unenforceable. If any provision or portion of any provision of this Agreement shall be held to be illegal, invalid or unenforceable by a court of competent jurisdiction, it is the intention of the parties that the remaining provisions or portions thereof shall constitute their agreement with respect to the subject matter hereof, and all such remaining provisions or portions thereof shall remain in full force and effect.</p>
<h2 class="text-lg mt-4">Changes and amendments</h2>
<p>We reserve the right to modify this Agreement or its policies relating to the Website or Services at any time, effective upon posting of an updated version of this Agreement on the Website. When we do, we will revise the updated date at the bottom of this page. Continued use of the Website after any such changes shall constitute your consent to such changes. Policy was created with <a style="color:inherit" target="_blank" title="Create terms and conditions" href="https://www.websitepolicies.com/blog/sample-terms-conditions-template">WebsitePolicies</a>.</p>
<h2 class="text-lg mt-4">Acceptance of these terms</h2>
<p>You acknowledge that you have read this Agreement and agree to all its terms and conditions. By using the Website or its Services you agree to be bound by this Agreement. If you do not agree to abide by the terms of this Agreement, you are not authorized to use or access the Website and its Services.</p>
<h2 class="text-lg mt-4">Contacting us</h2>
<p>If you would like to contact us to understand more about this Agreement or wish to contact us concerning any matter relating to it, you may send an email to &#116;&#111;s&#64;&#104;&#101;&#108;p&#109;e&#116;o&#46;&#108;i&#118;e</p>
<p>This document was last updated on March 19, 2020</p>

app/views/needs/_form.html.erb
<h1 class="text-4xl text-center mt-4"><%= t('.ask_help') %></h1>
<h4 class="text-gray-800 text-center text-2xl">
  <%= t('.fill_in_request') %>
</h4>

<div data-controller='edit-location' data-edit-location-lat='<%= @need.lc_lat %>' data-edit-location-lng='<%= @need.lc_lng %>'>
  <%= form_with(model: @need, url: my_need_path, method: :patch) do |f| %>
    <%= f.label :description, t('.describe_request'), class: 'text-xl mt-8' %>
    <%= f.text_area :description, autofocus: true, placeholder: t('.describe_request_placeholder') %>
    <% if @need.errors[:description] %>
      <p class="text-red-500"><%= @need.errors[:description].join(', ') %></p>
    <% end %>
    <%= f.hidden_field :lc_lat, 'data-target' => 'edit-location.latInput' %>
    <%= f.hidden_field :lc_lng, 'data-target' => 'edit-location.lngInput' %>

    <p class="mt-8 text-xl"><%= t('.location_html') %></p>
    <div data-target="edit-location.map" class="w-full h-50vh"></div>
    <% if @need.errors[:location] %>
      <p class="text-red-500"><%= @need.errors[:location].join(', ') %></p>
    <% end %>

    <%= f.submit t('common.save'), class: "submit block mx-auto p-8" %>
  <% end %>
</div>

app/views/needs/edit.html.erb
<%= render 'form' %>

app/views/needs/index.html.erb
<h1 class="text-4xl text-center mt-4"><%= t('.view_requests') %></h1>

<h4 class="text-xl"><%= t('.n_requests', count: @needs.length) %></h4>

<div
  class="w-full h-50vh"
  data-controller="needs-map"
  data-needs-map-list='<%= @needs_json %>'
  data-needs-map-lat="<%= current_user.lc_lat %>"
  data-needs-map-lng="<%= current_user.lc_lng %>"
></div>

app/views/needs/new.html.erb
<%= render 'form' %>

app/views/needs/show.html.erb
<h1 class="text-4xl text-center mt-4">
<% if current_user.need&.id == @need.id %>
  <%= t('.view_your_request') %>
<% else %>
  <%= t('.view_request') %>
<% end %>

<% if policy(@need).edit? %>
  <div class="flex justify-center mt-8">
    <%= link_to t('.edit_your_request'), edit_my_need_path, class: 'p-8 bg-blue-500 block text-white text-xl' %>
    <%= button_to t('.delete_your_request'), my_need_path, method: :delete, 'data-confirm': t('common.confirm'), class: 'ml-2 p-8 bg-red-500 block text-white text-xl' %>
  </div>
  <% if (offers = @need.offers).length > 0 %>
    <h3 class="text-xl text-center my-4"><%= t('.you_got_proposal', count: @need.offers.length) %>:</h3>
    <h4 class="text-lg text-center my-4"><%= t('.proposal_instructions') %></h4>
    <% offers.each do |offer| %>
      <p class="text-center font-bold text-lg"><%= t('.contact') %>: <%= offer.contact_info %></p>
      <p class="italic text-center mb-4"><%= offer.message %></p>
    <% end %>
  <% end %>
<% end %>

<h3 class="text-xl italic text-center mt-4">
  <%= @need.description %>
</h3>

<div class="w-full h-50vh mt-8" data-controller="show-map" data-lat="<%= @need.lc_lat %>" data-lng="<%= @need.lc_lng %>"></div>

<% if current_user.volunteer? %>
  <% if (offer = @need.offers.find_by(user_id: current_user.id)) %>
    <h3 class="text-xl text-center"><%= t('.already_sent') %></h3>
    <p class="italic text-center"><%= offer.message %> (<%= offer.contact_info %>)</p>
  <% else %>
    <h3 class="text-xl text-center mt-4"><%= t('.send_now') %></h3>
    <div class="mx-auto w-full md:w-1/2">
      <%= form_with(model: [@need, Offer.new]) do |f| %>
        <%= f.label :contact_info, t('.contact_info') %>
        <%= f.text_field :contact_info, class: 'string mb-4' %>
        <%= f.label :message, t('.message') %>
        <%= f.text_area :message %>
        <%= f.submit t('common.send'), class: 'submit block mx-auto' %>
      <% end %>
    </div>
  <% end %>
<% end %>

app/views/profiles/edit.html.erb
<h3 class="text-4xl text-center mt-12"><%= t('.are_you') %></h3>

<div class="grid grid-cols-2 gap-4 mt-4 text-center">
  <%= link_to t('.recipient'), edit_recipient_profile_path, class: 'block p-8 bg-blue-500 text-3xl text-white font-bold' %>
  <%= link_to t('.volunteer'), edit_volunteer_profile_path, class: 'block p-8 bg-blue-500 text-3xl text-white font-bold' %>
</div>

app/views/profiles/edit_recipient.html.erb
<h3 class="text-2xl text-center mt-12"><%= t('.need_details') %></h3>

<%= form_with(model: current_user, url: profile_path, class: 'flex flex-col justify-between mx-auto w-full md:w-1/2') do |f| %>
  <%= f.label :name, t('.name'), class: 'text-xl mt-8' %>
  <%= f.text_field :name, class: 'string', placeholder: t('.name_placeholder'), autofocus: true %>
  <% if current_user.errors[:name] %>
    <p class="text-red-500"><%= current_user.errors[:name].join(', ') %></p>
  <% end %>
  <%= f.label :bio, t('.bio'), class: 'text-xl mt-8' %>
  <p><%= t('.bio_questions') %></p>
  <%= f.text_area :bio, placeholder: t('.bio_placeholder') %>
  <% if current_user.errors[:bio] %>
    <p class="text-red-500"><%= current_user.errors[:bio].join(', ') %></p>
  <% end %>
  <%= f.submit t('common.save'), class: "rounded bg-blue-600 px-6 py-2 text-2xl mt-8 text-white self-center cursor-pointer" %>
<% end %>

app/views/profiles/edit_volunteer.html.erb
<h3 class="text-xl text-center mt-12"><%= t('.need_details') %></h3>

<div
  class="mx-auto w-full md:w-1/2"
  data-controller='edit-location'
  data-edit-location-lat='<%= current_user.lc_lat %>'
  data-edit-location-lng='<%= current_user.lc_lng %>'>
  <%= form_with(model: current_user, url: profile_path, class: 'flex flex-col justify-between items-center') do |f| %>
    <div class="my-4 self-stretch">
      <%= f.label :name, t('.name') %>
      <%= f.text_field :name, class: 'string' %>
      <% if current_user.errors[:name] %>
        <p class="text-red-500"><%= current_user.errors[:name].join(', ') %></p>
      <% end %>
    </div>
    <div class="my-4">
      <%= f.label :bio, t('.bio') %>
      <p class="text-gray-600 text-sm">
        <%= t('.bio_questions') %>
      </p>
      <%= f.text_area :bio %>
      <% if current_user.errors[:bio] %>
        <p class="text-red-500"><%= current_user.errors[:bio].join(', ') %></p>
      <% end %>
      <%= f.hidden_field :lc_lat, 'data-target' => 'edit-location.latInput' %>
      <%= f.hidden_field :lc_lng, 'data-target' => 'edit-location.lngInput' %>

      <p class="mt-8 text-lg">
        <%= t('.location') %>
      </p>
      <div data-target="edit-location.map" class="w-full h-50vh"></div>
      <% if current_user.errors[:location] %>
        <p class="text-red-500"><%= current_user.errors[:location].join(', ') %></p>
      <% end %>
    </div>
    <%= f.submit t('common.save'), class: "rounded bg-blue-600 px-6 py-2 text-xl mt-8 text-white" %>
  <% end %>
</div>